import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/Header";

const Avenir = localFont({
  src: "./fonts/Avenir.otf",
  variable: "--font-avenir",
});
const MabryPro = localFont({
  src: "./fonts/MabryPro.ttf",
  variable: "--font-mabrypro",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// tambahin children nanti
export default function RootLayout({ children }) {
  return (
    <html lang="id" className={ `${Avenir.variable} ${MabryPro.variable} antialiased` }>
      <body className="font-[family-name:var(--font-mabrypro)]">
        <Header />
        { children }
      </body>
    </html>
  );
}
